#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="${JOB_AGENT_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"
ENV_FILE="${JOB_AGENT_ENV_FILE:-$ROOT/.env.local}"
SCHEDULE_FILE="${JOB_AGENT_SCHEDULE_FILE:-$ROOT/.schedule.local}"
SCHEDULER_DIR="${JOB_AGENT_SCHEDULER_DIR:-$ROOT/.scheduler}"
PLIST_FILE="$SCHEDULER_DIR/com.jvdh.jobsearch.scheduler.plist"
CRON_FILE="$SCHEDULER_DIR/cron.entry"
APPARMOR_PROFILE_FILE="$SCHEDULER_DIR/bwrap-userns-restrict"
PLATFORM="${JOB_AGENT_PLATFORM:-$(uname -s)}"
LOGSEQ_GRAPH_DIR_VALUE=""
CODEX_BIN_VALUE=""
ENV_CODEX_BIN_VALUE="${CODEX_BIN:-}"
ENV_LOGSEQ_GRAPH_DIR_VALUE="${LOGSEQ_GRAPH_DIR:-}"
SMTP_HOST_VALUE=""
SMTP_PORT_VALUE=""
SMTP_FROM_VALUE=""
SMTP_TO_VALUE=""
SMTP_USERNAME_VALUE=""
SMTP_PASSWORD_VALUE=""
SMTP_TLS_VALUE=""
ENV_SMTP_HOST_VALUE="${JOB_AGENT_SMTP_HOST:-}"
ENV_SMTP_PORT_VALUE="${JOB_AGENT_SMTP_PORT:-}"
ENV_SMTP_FROM_VALUE="${JOB_AGENT_SMTP_FROM:-}"
ENV_SMTP_TO_VALUE="${JOB_AGENT_SMTP_TO:-}"
ENV_SMTP_USERNAME_VALUE="${JOB_AGENT_SMTP_USERNAME:-}"
ENV_SMTP_PASSWORD_VALUE="${JOB_AGENT_SMTP_PASSWORD:-}"
ENV_SMTP_TLS_VALUE="${JOB_AGENT_SMTP_TLS:-}"

usage() {
  cat <<EOF
Usage: $0 [--codex-bin <path>] [--logseq-graph-dir <path>]

Create or refresh machine-local scheduler config for this checkout.
In a terminal, the script prompts for any missing required values.
In non-interactive mode, CODEX_BIN must be supplied or discoverable.
This script does not install cron or launchd. After adding entries to
$SCHEDULE_FILE with scripts/configure_schedule.py or the setup agent, run
scripts/install_scheduler.sh.
EOF
}

shell_escape() {
  printf '%q' "$1"
}

is_interactive() {
  [[ -t 0 && -t 1 ]]
}

resolve_command_path() {
  local candidate="${1:-}"
  if [[ -z "$candidate" ]]; then
    return 1
  fi
  if [[ "$candidate" == */* ]]; then
    if [[ -x "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
    return 1
  fi
  if command -v "$candidate" >/dev/null 2>&1; then
    command -v "$candidate"
    return 0
  fi
  return 1
}

canonicalize_linux_executable_path() {
  local candidate="${1:-}"
  local resolved=""

  if [[ -z "$candidate" ]]; then
    return 1
  fi

  if [[ "$PLATFORM" != "Linux" ]] || ! command -v readlink >/dev/null 2>&1; then
    printf '%s\n' "$candidate"
    return 0
  fi

  resolved="$(readlink -f "$candidate" 2>/dev/null || true)"
  if [[ -n "$resolved" && -x "$resolved" ]]; then
    printf '%s\n' "$resolved"
    return 0
  fi

  printf '%s\n' "$candidate"
}

detect_codex_bin() {
  local detected=""

  if ! detected="$(resolve_command_path codex 2>/dev/null)"; then
    return 1
  fi

  canonicalize_linux_executable_path "$detected"
}

detect_bwrap_bin() {
  local detected=""

  if [[ "$PLATFORM" != "Linux" ]]; then
    return 1
  fi

  if ! detected="$(resolve_command_path bwrap 2>/dev/null)"; then
    return 1
  fi

  canonicalize_linux_executable_path "$detected"
}

write_bwrap_apparmor_profile() {
  local bwrap_bin="$1"

  cat >"$APPARMOR_PROFILE_FILE" <<EOF
# Generated by scripts/setup_machine.sh.
# Install this profile on Linux hosts that restrict unprivileged user
# namespaces via AppArmor before running Codex sandboxing through bwrap.
abi <abi/4.0>,

include <tunables/global>

$bwrap_bin flags=(unconfined) {
  userns create,

  # Site-specific additions and overrides.
  include if exists <local/bwrap-userns-restrict>
}
EOF
}

detect_logseq_graph_dir() {
  local home_dir="${HOME:-}"
  local candidate
  for candidate in \
    "$home_dir/Documents/logseq" \
    "$home_dir/Documents/Logseq"
  do
    if [[ -d "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

prompt_line() {
  local prompt="$1"
  local value
  printf '%s' "$prompt" >&2
  IFS= read -r value
  printf '%s\n' "$value"
}

prompt_for_codex_bin() {
  local default_value="${1:-}"
  local entered=""
  local candidate=""
  local resolved=""

  while true; do
    if [[ -n "$default_value" ]]; then
      entered="$(prompt_line "CODEX_BIN [$default_value]: ")"
      candidate="${entered:-$default_value}"
    else
      entered="$(prompt_line "CODEX_BIN (required): ")"
      candidate="$entered"
    fi

    if resolve_command_path "$candidate" >/dev/null 2>&1; then
      resolved="$(resolve_command_path "$candidate")"
      printf '%s\n' "$resolved"
      return 0
    fi

    echo "CODEX_BIN must point to an executable codex binary." >&2
  done
}

prompt_for_logseq_graph_dir() {
  local default_value="${1:-}"
  local entered=""

  if [[ -n "$default_value" ]]; then
    entered="$(prompt_line "LOGSEQ_GRAPH_DIR (optional, Enter to use $default_value, type skip to leave unset): ")"
    if [[ -z "$entered" ]]; then
      printf '%s\n' "$default_value"
      return 0
    fi
  else
    entered="$(prompt_line "LOGSEQ_GRAPH_DIR (optional, blank to skip): ")"
    if [[ -z "$entered" ]]; then
      printf '\n'
      return 0
    fi
  fi

  case "$entered" in
    skip|SKIP|none|NONE)
      printf '\n'
      ;;
    *)
      printf '%s\n' "$entered"
      ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --codex-bin)
      CODEX_BIN_VALUE="${2:?missing value for --codex-bin}"
      shift 2
      ;;
    --logseq-graph-dir)
      LOGSEQ_GRAPH_DIR_VALUE="${2:?missing value for --logseq-graph-dir}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
done

ORIGINAL_PATH="$PATH"
existing_path="$ORIGINAL_PATH"
existing_codex_bin=""
existing_logseq_graph_dir=""
existing_smtp_host=""
existing_smtp_port=""
existing_smtp_from=""
existing_smtp_to=""
existing_smtp_username=""
existing_smtp_password=""
existing_smtp_tls=""
detected_codex_bin=""
detected_logseq_graph_dir=""
detected_bwrap_bin=""

if [[ -f "$ENV_FILE" ]]; then
  set +u
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set -u
  existing_path="${PATH:-$ORIGINAL_PATH}"
  existing_codex_bin="${CODEX_BIN:-}"
  existing_logseq_graph_dir="${LOGSEQ_GRAPH_DIR:-}"
  existing_smtp_host="${JOB_AGENT_SMTP_HOST:-}"
  existing_smtp_port="${JOB_AGENT_SMTP_PORT:-}"
  existing_smtp_from="${JOB_AGENT_SMTP_FROM:-}"
  existing_smtp_to="${JOB_AGENT_SMTP_TO:-}"
  existing_smtp_username="${JOB_AGENT_SMTP_USERNAME:-}"
  existing_smtp_password="${JOB_AGENT_SMTP_PASSWORD:-}"
  existing_smtp_tls="${JOB_AGENT_SMTP_TLS:-}"
  PATH="$ORIGINAL_PATH"
fi

if [[ -z "$CODEX_BIN_VALUE" ]]; then
  CODEX_BIN_VALUE="$ENV_CODEX_BIN_VALUE"
fi
if [[ -z "$CODEX_BIN_VALUE" ]]; then
  CODEX_BIN_VALUE="$existing_codex_bin"
fi
if detected_codex_bin="$(detect_codex_bin 2>/dev/null)"; then
  :
else
  detected_codex_bin=""
fi

if [[ -z "$LOGSEQ_GRAPH_DIR_VALUE" ]]; then
  LOGSEQ_GRAPH_DIR_VALUE="$ENV_LOGSEQ_GRAPH_DIR_VALUE"
fi
if [[ -z "$LOGSEQ_GRAPH_DIR_VALUE" ]]; then
  LOGSEQ_GRAPH_DIR_VALUE="$existing_logseq_graph_dir"
fi
if detected_logseq_graph_dir="$(detect_logseq_graph_dir 2>/dev/null)"; then
  :
else
  detected_logseq_graph_dir=""
fi
if detected_bwrap_bin="$(detect_bwrap_bin 2>/dev/null)"; then
  :
else
  detected_bwrap_bin=""
fi

SMTP_HOST_VALUE="${ENV_SMTP_HOST_VALUE:-$existing_smtp_host}"
SMTP_PORT_VALUE="${ENV_SMTP_PORT_VALUE:-$existing_smtp_port}"
SMTP_FROM_VALUE="${ENV_SMTP_FROM_VALUE:-$existing_smtp_from}"
SMTP_TO_VALUE="${ENV_SMTP_TO_VALUE:-$existing_smtp_to}"
SMTP_USERNAME_VALUE="${ENV_SMTP_USERNAME_VALUE:-$existing_smtp_username}"
SMTP_PASSWORD_VALUE="${ENV_SMTP_PASSWORD_VALUE:-$existing_smtp_password}"
SMTP_TLS_VALUE="${ENV_SMTP_TLS_VALUE:-$existing_smtp_tls}"

if [[ -z "$CODEX_BIN_VALUE" ]]; then
  if is_interactive; then
    CODEX_BIN_VALUE="$(prompt_for_codex_bin "$detected_codex_bin")"
  elif [[ -n "$detected_codex_bin" ]]; then
    CODEX_BIN_VALUE="$detected_codex_bin"
  else
    echo "CODEX_BIN is required in non-interactive mode; pass --codex-bin or add codex to PATH." >&2
    exit 1
  fi
fi

if resolve_command_path "$CODEX_BIN_VALUE" >/dev/null 2>&1; then
  CODEX_BIN_VALUE="$(resolve_command_path "$CODEX_BIN_VALUE")"
elif is_interactive; then
  CODEX_BIN_VALUE="$(prompt_for_codex_bin "$detected_codex_bin")"
else
  echo "CODEX_BIN '$CODEX_BIN_VALUE' is not executable or not found on PATH." >&2
  exit 1
fi

if [[ -z "$LOGSEQ_GRAPH_DIR_VALUE" && is_interactive ]]; then
  LOGSEQ_GRAPH_DIR_VALUE="$(prompt_for_logseq_graph_dir "$detected_logseq_graph_dir")"
fi

mkdir -p "$SCHEDULER_DIR/state" "$ROOT/logs"

{
  echo "# Machine-local configuration for this checkout."
  echo "# Generated by scripts/setup_machine.sh."
  printf 'export JOB_AGENT_ROOT=%s\n' "$(shell_escape "$ROOT")"
  printf 'export PATH=%s\n' "$(shell_escape "$existing_path")"
  echo "# Required: executable codex binary for scheduled runs."
  printf 'export CODEX_BIN=%s\n' "$(shell_escape "$CODEX_BIN_VALUE")"
  echo "# Optional: Logseq graph root for digest publication."
  if [[ -n "$LOGSEQ_GRAPH_DIR_VALUE" ]]; then
    printf 'export LOGSEQ_GRAPH_DIR=%s\n' "$(shell_escape "$LOGSEQ_GRAPH_DIR_VALUE")"
  else
    echo "# export LOGSEQ_GRAPH_DIR=/absolute/path/to/logseq"
  fi
  echo "# Optional: SMTP settings for email delivery."
  echo "# Keep real SMTP secrets in this gitignored local file; do not paste passwords into chat."
  if [[ -n "$SMTP_HOST_VALUE" ]]; then
    printf 'export JOB_AGENT_SMTP_HOST=%s\n' "$(shell_escape "$SMTP_HOST_VALUE")"
  else
    echo "# export JOB_AGENT_SMTP_HOST=smtp.example.com"
  fi
  if [[ -n "$SMTP_PORT_VALUE" ]]; then
    printf 'export JOB_AGENT_SMTP_PORT=%s\n' "$(shell_escape "$SMTP_PORT_VALUE")"
  else
    echo "# export JOB_AGENT_SMTP_PORT=587"
  fi
  if [[ -n "$SMTP_FROM_VALUE" ]]; then
    printf 'export JOB_AGENT_SMTP_FROM=%s\n' "$(shell_escape "$SMTP_FROM_VALUE")"
  else
    echo "# export JOB_AGENT_SMTP_FROM=jobs@example.com"
  fi
  if [[ -n "$SMTP_TO_VALUE" ]]; then
    printf 'export JOB_AGENT_SMTP_TO=%s\n' "$(shell_escape "$SMTP_TO_VALUE")"
  else
    echo "# export JOB_AGENT_SMTP_TO=you@example.com"
  fi
  if [[ -n "$SMTP_USERNAME_VALUE" ]]; then
    printf 'export JOB_AGENT_SMTP_USERNAME=%s\n' "$(shell_escape "$SMTP_USERNAME_VALUE")"
  else
    echo "# export JOB_AGENT_SMTP_USERNAME=jobs@example.com"
  fi
  if [[ -n "$SMTP_PASSWORD_VALUE" ]]; then
    printf 'export JOB_AGENT_SMTP_PASSWORD=%s\n' "$(shell_escape "$SMTP_PASSWORD_VALUE")"
  else
    echo "# export JOB_AGENT_SMTP_PASSWORD=app-password"
  fi
  if [[ -n "$SMTP_TLS_VALUE" ]]; then
    printf 'export JOB_AGENT_SMTP_TLS=%s\n' "$(shell_escape "$SMTP_TLS_VALUE")"
  else
    echo "# export JOB_AGENT_SMTP_TLS=starttls"
  fi
} >"$ENV_FILE"

if [[ -n "$detected_bwrap_bin" ]]; then
  write_bwrap_apparmor_profile "$detected_bwrap_bin"
else
  rm -f "$APPARMOR_PROFILE_FILE"
fi

if [[ ! -f "$SCHEDULE_FILE" ]]; then
  cat >"$SCHEDULE_FILE" <<EOF
# Machine-local scheduler entries.
# Prefer scripts/configure_schedule.py or the setup agent over hand-editing.
# Formats:
# daily HH:MM track <track-slug> [--delivery logseq|email]...
# weekly mon HH:MM track <track-slug> [--delivery logseq|email]...
# monthly 1 HH:MM track <track-slug> [--delivery logseq|email]...
# Example:
# daily 08:00 track core_crypto
# weekly mon 08:00 track core_crypto --delivery logseq --delivery email
EOF
fi

runner_path="$ROOT/scripts/run_scheduled_jobs.sh"
stdout_log="$ROOT/logs/scheduler.out"
stderr_log="$ROOT/logs/scheduler.err"

{
  echo "# BEGIN jobsearch scheduler"
  printf '* * * * * /bin/bash %s >>%s 2>>%s\n' \
    "$(shell_escape "$runner_path")" \
    "$(shell_escape "$stdout_log")" \
    "$(shell_escape "$stderr_log")"
  echo "# END jobsearch scheduler"
} >"$CRON_FILE"

cat >"$PLIST_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <!-- Generated by scripts/setup_machine.sh. -->
  <dict>
    <key>Label</key>
    <string>com.jvdh.jobsearch.scheduler</string>

    <key>ProgramArguments</key>
    <array>
      <string>/bin/bash</string>
      <string>$runner_path</string>
    </array>

    <key>EnvironmentVariables</key>
    <dict>
      <key>HOME</key>
      <string>${HOME:-$ROOT}</string>
      <key>PATH</key>
      <string>$existing_path</string>
    </dict>

    <key>WorkingDirectory</key>
    <string>$ROOT</string>

    <key>StartInterval</key>
    <integer>60</integer>

    <key>StandardOutPath</key>
    <string>$stdout_log</string>

    <key>StandardErrorPath</key>
    <string>$stderr_log</string>
  </dict>
</plist>
EOF

echo "Wrote $ENV_FILE"
echo "Prepared $SCHEDULE_FILE"
echo "Generated $CRON_FILE"
echo "Generated $PLIST_FILE"
if [[ -f "$APPARMOR_PROFILE_FILE" ]]; then
  echo "Generated $APPARMOR_PROFILE_FILE for $detected_bwrap_bin"
  echo "Run sudo bash scripts/install_bwrap_apparmor.sh if this Linux host enforces AppArmor userns restrictions."
fi
echo "Use scripts/configure_schedule.py or the setup agent to add track entries, then run scripts/install_scheduler.sh."
